USE [Outorga]
GO

SET IDENTITY_INSERT [dbo].[TIPO_INTERFERENCIA] ON 

INSERT [dbo].[TIPO_INTERFERENCIA] ([ID_TIPO_INTERFERENCIA], [DESCRICAO]) VALUES (1, N'Superficial')
INSERT [dbo].[TIPO_INTERFERENCIA] ([ID_TIPO_INTERFERENCIA], [DESCRICAO]) VALUES (2, N'Subterrânea')
INSERT [dbo].[TIPO_INTERFERENCIA] ([ID_TIPO_INTERFERENCIA], [DESCRICAO]) VALUES (3, N'Lançamento de Águas Pluviais')
INSERT [dbo].[TIPO_INTERFERENCIA] ([ID_TIPO_INTERFERENCIA], [DESCRICAO]) VALUES (4, N'Canal')
INSERT [dbo].[TIPO_INTERFERENCIA] ([ID_TIPO_INTERFERENCIA], [DESCRICAO]) VALUES (5, N'Caminhão Pipa')
INSERT [dbo].[TIPO_INTERFERENCIA] ([ID_TIPO_INTERFERENCIA], [DESCRICAO]) VALUES (6, N'Lançamento de Efluentes')
INSERT [dbo].[TIPO_INTERFERENCIA] ([ID_TIPO_INTERFERENCIA], [DESCRICAO]) VALUES (7, N'Barragem')
SET IDENTITY_INSERT [dbo].[TIPO_INTERFERENCIA] OFF
SET IDENTITY_INSERT [dbo].[Tipo_Outorga] ON 
GO


